Errors at compile time with NS >= 3.17:
    File "/home/ju/doctorat/ns3/ns-allinone-3.17/ns-3.17/src/plc/wscript", line 49, in build
      headers = bld.new_task_gen(features=['ns3header'])
  AttributeError: 'BuildContext' object has no attribute 'new_task_gen'

Solution found:

  Use directly bld() instead of bld.new_task_gen().
  See https://groups.google.com/forum/#!msg/ns-3-users/JzUvWiWn9UY/dLn3AMMIdt0J